language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get install libmagic-dev libjansson-dev

install:
  - python setup.py build --enable-magic --enable-cuckoo
  - python setup.py install

script:
  - python tests.py
